import type { Metadata } from "next";
import "./globals.css";
import Link from 'next/link';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <header style={{ padding: '20px', backgroundColor: '#f0f0f0', borderBottom: '1px solid #ccc' }}>
          <nav>
            <Link href="/" style={{ marginRight: '20px' }}>Page 1</Link>
            <Link href="/test">Page 2</Link>
          </nav>
        </header>

        {/* Main content */}
        <main>{children}</main>

        {/* Footer */}
        <footer style={{ padding: '20px', backgroundColor: '#f0f0f0', borderTop: '1px solid #ccc' }}>
          <p>© {new Date().getFullYear()} My Next.js App</p>
        </footer>
      </body>
    </html>
  );
}
